spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    application:
      name: request-service

  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/ewm-request-db
    username: request
    password: request

logging:
  level:
    "org.springframework.orm.jpa": INFO
    "org.springframework.transaction": INFO
    "org.springframework.transaction.interceptor": TRACE
    "org.springframework.orm.jpa.JpaTransactionManager": DEBUG
    "org.hibernate.SQL": DEBUG
    "org.hibernate.orm.jdbc.bind": trace

discovery:
  services:
    stats-server-id: STATS-SERVER

server:
  port: 0