-- Таблица запросов
CREATE TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP,
    event_id INTEGER,
    requester_id INTEGER,
    status varchar(25) NOT NULL
);